# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      app.deploy.manager:
       class: AppBundle\Deploy\DeployManager
       arguments: ["@app.operations.downloader","@app.operations.extractor","@app.operations.rsync","@app.operations.chown","@app.operations.remover"]
      app.operations.downloader:
       class: AppBundle\Operations\Downloader
      app.operations.extractor:
       class: AppBundle\Operations\Extractor
      app.operations.rsync:
       class: AppBundle\Operations\Rsync
      app.operations.remover:
       class: AppBundle\Operations\Remover
      app.operations.chown:
       class: AppBundle\Operations\Chown
